Kimlik={"İsim":"Serhat",
        "Soyisim":"Özdemir",
        "Yas":28,
        "Doğum yeri":"Kadıkoy"}
print(Kimlik)
print(Kimlik["İsim"])
Kimlik["İsim"]="Murat"
print(Kimlik)
Kullanıcılar={"Ahmetcan":{
    "Tc_no":2482726526,
    "D_yeri":"Ankara",
    "Yas":24
},
"Arzu":{
    "Tc_no":7463464786,
    "D_yeri":"Bayburt",
    "Yas":43
}
}
print(Kullanıcılar["Ahmetcan"])